spring:
  jpa:
    properties:
      hibernate:
        column_ordering_strategy:  legacy
    show-sql:  true
    hibernate:
      ddl-auto:  create
  datasource:
    url:  jdbc:mysql://localhost:3306/hwealth_Medico
    username:  root
    password:  
    driver-class-name:   com.mysql.cj.jdbc.Driver 
  application:
    name:  Customer Application
server:
  port:  8080
  
  
#spring.jpa.properties.hibernate.column_ordering_strategy=legacy  

       